# Generated by Django 3.1.7 on 2021-04-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address_ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
