# Generated by Django 3.2 on 2021-06-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0002_auto_20210417_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address_ip', models.CharField(max_length=15)),
                ('address_mac', models.CharField(max_length=12)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netos.device')),
            ],
        ),
    ]
