# Generated by Django 3.2 on 2021-06-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0004_rename_ip_address_useripaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Useripaddress',
            new_name='Labipaddress',
        ),
    ]
