# Generated by Django 3.2 on 2021-08-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0005_rename_useripaddress_labipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='labipaddress',
            options={'verbose_name': 'Labipaddress', 'verbose_name_plural': 'Labipaddresses'},
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labipaddress',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='labipaddress',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netos.device'),
        ),
        migrations.AlterField(
            model_name='labipaddress',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='labipaddress',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netos.category'),
        ),
    ]
