# Generated by Django 3.2 on 2021-08-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0006_auto_20210824_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labipaddress',
            name='category',
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netos.category'),
        ),
    ]
